set(DEBUG_UART_PORT "uart0" CACHE STRING "Debug UART port")
set(DEBUG_UART_SPEED "115200" CACHE STRING "Debug UART speed")
set(DEBUG_UART_PIN_TX "0" CACHE STRING "Debug UART TX pin")
set(DEBUG_UART_PIN_RX "1" CACHE STRING "Debug UART RX pin")

set(GPS_UART_PORT "uart1" CACHE STRING "GPS UART port")
set(GPS_UART_SPEED "9600" CACHE STRING "GPS UART speed")
set(GPS_UART_PIN_TX "8" CACHE STRING "GPS UART TX pin")
set(GPS_UART_PIN_RX "9" CACHE STRING "GPS UART RX pin")
set(GPS_UART_DATA_BITS "8" CACHE STRING "GPS UART data bits")
set(GPS_UART_STOP_BITS "1" CACHE STRING "GPS UART stop bits")
set(GPS_UART_PARITY "UART_PARITY_NONE" CACHE STRING "GPS UART stop bits")

set(DISPLAY_PIN_RS "17" CACHE STRING "Display RS pin")
set(DISPLAY_PIN_ENABLE "16" CACHE STRING "Display Enable pin")
set(DISPLAY_PIN_D4 "21" CACHE STRING "Display D4 pin")
set(DISPLAY_PIN_D5 "20" CACHE STRING "Display D5 pin")
set(DISPLAY_PIN_D6 "19" CACHE STRING "Display D6 pin")
set(DISPLAY_PIN_D7 "18" CACHE STRING "Display D7 pin")

set(LED_PIN_GPS_UART "4" CACHE STRING "LED GPS UART pin")
set(LED_PIN_GPS_VALID "5" CACHE STRING "LED GPS Valid pin")
set(LED_PIN_GPS_PPS "6" CACHE STRING "LED GPS PPS pin")
set(LED_PIN_RTC_SYNC "7" CACHE STRING "LED RTC sync pin")

set(COUNTER_PIN_CLOCK "3" CACHE STRING "Counter clock pin")
set(COUNTER_PIN_PPS "22" CACHE STRING "Counter PPS pin")

set(SI5351_BUS "i2c0" CACHE STRING "Si5351 oscillator I2C bus")
set(SI5351_BUS_PIN_SDA "12" CACHE STRING "Si5351 oscillator I2C bus SDA pin")
set(SI5351_BUS_PIN_SCL "13" CACHE STRING "Si5351 oscillator I2C bus SCL pin")
set(SI5351_BAUDRATE "400000" CACHE STRING "Si5351 oscillator I2C bus baudrate")
set(SI5351_ADDRESS "0x60" CACHE STRING "Si5351 oscillator address on I2C bus")
set(SI5351_XTAL_FREQ "25000000" CACHE STRING "Si5351 oscillator crystal frequency")
set(SI5351_XTAL_FREQ_CORRECTION "0" CACHE STRING "Si5351 oscillator crystal frequency correction in parts per million (ppm)")
set(SI5351_FREQ_CLK0 "40000000" CACHE STRING "Si5351 oscillator clock 0 frequency")
set(SI5351_FREQ_CLK1 "25000000" CACHE STRING "Si5351 oscillator clock 1 frequency")
set(SI5351_FREQ_CLK2 "10000000" CACHE STRING "Si5351 oscillator clock 2 frequency")

if (NOT (DEBUG_UART_PORT STREQUAL "uart0" OR DEBUG_UART_PORT STREQUAL "uart1"))
    message(FATAL_ERROR "Invalid DEBUG_UART_PORT value: ${DEBUG_UART_PORT}. Must be uart0 or uart1")
endif ()

if (DEBUG_UART_PORT STREQUAL GPS_UART_PORT)
    message(FATAL_ERROR "DEBUG_UART_PORT and GPS_UART_PORT must not be equal (both are ${DEBUG_UART_PORT})")
endif ()

if (GPS_UART_PORT STREQUAL "uart0")
    add_compile_definitions(GPS_UART_IRQ=UART0_IRQ)
elseif (GPS_UART_PORT STREQUAL "uart1")
    add_compile_definitions(GPS_UART_IRQ=UART1_IRQ)
else ()
    message(FATAL_ERROR "Invalid GPS_UART_PORT value: ${GPS_UART_PORT}. Must be uart0 or uart1")
endif ()

if (NOT (SI5351_BUS STREQUAL "i2c0" OR SI5351_BUS STREQUAL "i2c1"))
    message(FATAL_ERROR "Invalid SI5351_BUS value: ${SI5351_BUS}. Must be i2c0 or i2c1")
endif ()

add_compile_definitions(
        DEBUG_UART_PORT=${DEBUG_UART_PORT}
        DEBUG_UART_SPEED=${DEBUG_UART_SPEED}
        DEBUG_UART_PIN_TX=${DEBUG_UART_PIN_TX}
        DEBUG_UART_PIN_RX=${DEBUG_UART_PIN_RX}

        DISPLAY_PIN_RS=${DISPLAY_PIN_RS}
        DISPLAY_PIN_ENABLE=${DISPLAY_PIN_ENABLE}
        DISPLAY_PIN_D4=${DISPLAY_PIN_D4}
        DISPLAY_PIN_D5=${DISPLAY_PIN_D5}
        DISPLAY_PIN_D6=${DISPLAY_PIN_D6}
        DISPLAY_PIN_D7=${DISPLAY_PIN_D7}

        GPS_UART_PORT=${GPS_UART_PORT}
        GPS_UART_SPEED=${GPS_UART_SPEED}
        GPS_UART_PIN_TX=${GPS_UART_PIN_TX}
        GPS_UART_PIN_RX=${GPS_UART_PIN_RX}
        GPS_UART_DATA_BITS=${GPS_UART_DATA_BITS}
        GPS_UART_STOP_BITS=${GPS_UART_STOP_BITS}
        GPS_UART_PARITY=${GPS_UART_PARITY}
        GPS_PPS_PIN=${GPS_PPS_PIN}

        LED_PIN_GPS_UART=${LED_PIN_GPS_UART}
        LED_PIN_GPS_VALID=${LED_PIN_GPS_VALID}
        LED_PIN_GPS_PPS=${LED_PIN_GPS_PPS}
        LED_PIN_RTC_SYNC=${LED_PIN_RTC_SYNC}

        COUNTER_PIN_CLOCK=${COUNTER_PIN_CLOCK}
        COUNTER_PIN_PPS=${COUNTER_PIN_PPS}

        SI5351_BUS=${SI5351_BUS}
        SI5351_BUS_PIN_SDA=${SI5351_BUS_PIN_SDA}
        SI5351_BUS_PIN_SCL=${SI5351_BUS_PIN_SCL}
        SI5351_BAUDRATE=${SI5351_BAUDRATE}
        SI5351_ADDRESS=${SI5351_ADDRESS}
        SI5351_XTAL_FREQ=${SI5351_XTAL_FREQ}
        SI5351_XTAL_FREQ_CORRECTION=${SI5351_XTAL_FREQ_CORRECTION}
        SI5351_FREQ_CLK0=${SI5351_FREQ_CLK0}
        SI5351_FREQ_CLK1=${SI5351_FREQ_CLK1}
        SI5351_FREQ_CLK2=${SI5351_FREQ_CLK2}
)
