set(LOG_LEVEL "TRACE" CACHE STRING "Enabled log level")
set_property(CACHE LOG_LEVEL PROPERTY STRINGS TRACE DEBUG INFO WARNING ERROR OFF)

if (LOG_LEVEL STREQUAL TRACE)
    add_definitions(-DLOG_TRACE_ENABLED)
    add_definitions(-DLOG_DEBUG_ENABLED)
    add_definitions(-DLOG_INFO_ENABLED)
    add_definitions(-DLOG_WARNING_ENABLED)
    add_definitions(-DLOG_ERROR_ENABLED)
elseif (LOG_LEVEL STREQUAL DEBUG)
    add_definitions(-DLOG_DEBUG_ENABLED)
    add_definitions(-DLOG_INFO_ENABLED)
    add_definitions(-DLOG_WARNING_ENABLED)
    add_definitions(-DLOG_ERROR_ENABLED)
elseif (LOG_LEVEL STREQUAL INFO)
    add_definitions(-DLOG_INFO_ENABLED)
    add_definitions(-DLOG_WARNING_ENABLED)
    add_definitions(-DLOG_ERROR_ENABLED)
elseif (LOG_LEVEL STREQUAL WARNING)
    add_definitions(-DLOG_WARNING_ENABLED)
    add_definitions(-DLOG_ERROR_ENABLED)
elseif (LOG_LEVEL STREQUAL ERROR)
    add_definitions(-DLOG_ERROR_ENABLED)
endif ()

set(LOG_GPS_ENABLED "TRUE" CACHE BOOL "Enabled logging on gps module")
set(LOG_LED_ENABLED "TRUE" CACHE BOOL "Enabled logging on led module")
set(LOG_COUNTER_ENABLED "TRUE" CACHE BOOL "Enabled logging on counter module")
set(LOG_OSCILLATOR_ENABLED "TRUE" CACHE BOOL "Enabled logging on oscillator module")
