execute_process(COMMAND date -u -Iseconds
        OUTPUT_VARIABLE APPLICATION_BUILD
        ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
message(STATUS "APPLICATION_BUILD: ${APPLICATION_BUILD}")

execute_process(COMMAND git describe --match=NeVeRmAtCh --always --abbrev=7 --dirty
        OUTPUT_VARIABLE APPLICATION_GIT_SHA1
        ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)
message(STATUS "APPLICATION_GIT_SHA1: ${APPLICATION_GIT_SHA1}")

set(APPLICATION_VERSION "${APPLICATION_VERSION_MAJOR}.${APPLICATION_VERSION_MINOR}.${APPLICATION_VERSION_PATCH}")

add_compile_definitions(
        APPLICATION_NAME="${APPLICATION_NAME}"
        APPLICATION_VERSION="${APPLICATION_VERSION}"
        ORGANIZATION_NAME="${ORGANIZATION_NAME}"
        ORGANIZATION_DOMAIN="${ORGANIZATION_DOMAIN}"

        APPLICATION_BUILD="${APPLICATION_BUILD}"
        APPLICATION_GIT_SHA1="${APPLICATION_GIT_SHA1}"
)
